apiVersion: apps/v1
kind: Deployment
metadata:
  name: lojo-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lojo-webapp-python
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: lojo-webapp-python
    spec:
      containers:
      - name: lojo-webapp-python
        image: lojoregistry.azurecr.io/lojo-webapp-python:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lojo-webapp-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: lojo-webapp-python